# Workshop 0 - Introduction to Python [1 Week]

## Objectives:

* Setup your tools and working environment: Anaconda distribution
* Join a group (you will work in groups of two) in consultation with your demonstrator.
* Access to online resources for learning Python programming
* A brief overview of Python basics.
* A simple exercise

> __Common objectives of all workshops:__
> Gain hands-on experience and learn by doing! Understand how theoretical knowledge discussed in lectures relates to practice. Develop motivation for gaining further theoretical and practical knowledge beyond the subject material.

## Table of contents
1. [Introduction](#Introduction)
    - [Motivation](#Motivation)
    - [Python version](#PythonVersion)
    - [Tools for Python Development](#Tools)
    - [Jupyter Notebook Quick Start](#Jupyter)
    - [Package management](#PackageManagement)
2. [Online Resources](#LearningPython)
3. [Elements of Python programming](#ElementsOfPythonProgramming)
    - [Variable assignment](#VariableAssignment)
    - [Basic Data Types](#BasicDataTypes)
    - [Data Structures Overview](#DataStructures)
    - [Conditional Statements](#ConditionalStatements)
    - [Functions](#Functions)
    - [Modules](#Modules)
    - [Classes and Objects](#ClassesandObjects)
    - [Special Functions](#SpecialFunctions)
4. [External Libraries](#Libraries)
    - [Numpy](#Numpy)
    - [Matplotlib](#Matplotlib)
    - [Scipy](#Scipy)
5. [Exercise - Number Guessing Game](#Exercise)

## Team  <a name="team"></a>

Lecturer: 
- Assoc. Prof. **Tansu Alpcan** 
- email: tansu.alpcan@unimelb.edu.au

Tutors:
- **Mr. Sandamal Weerasinghe**, email: pweerasinghe@student.unimelb.edu.au
- **Mr. Sergey Iakovlev**, email: siakovlev@student.unimelb.edu.au
- **Ms. Fateme Fahiman**, email: ffahiman@student.unimelb.edu.au

## Motivation  for learning Python <a name="Motivation"></a>

1. #1 in “2018 Top Programming Languages” by IEEE Spectrum: [link](https://spectrum.ieee.org/at-work/innovation/the-2018-top-programming-languages)

2. As of February 2019, the Python Package Index (PyPI), the official repository for third-party Python software, contains over 130,000 packages with a wide range of functionality ([link](http://www.modulecounts.com/))


3. Python is versatile language that is used for:
    - Data analysis
    - Web development
    - Trading, finance
    - Science
    - Scrypting (3ds Max, Maya, Inskape)
    - etc

4. Python has a broad standard library

5. Great first language to learn
    - Low syntactic overhead
    
6. Widely used in industry:
    - [Reddit](https://www.reddit.com/) is written entirely in Python
    - Google, Amazon, Instagram, NASA, Facebook, etc. use Python in development. 

### Python 2.x or 3.x? <a name="PythonVersion"></a>

- Python 2.x is legacy
- Python 3.x is the present and future of the language
    - There are a few minor downsides, such as very slightly worse library support

**We will be using the latest stable Python 3 release**

## Tools for Python development <a name="Tools"></a>

### Spyder IDE
- https://www.spyder-ide.org/
- Open-source, free Integrated Development Environment (IDE): https://www.spyder-ide.org/
    - Multi-language editor with features such as syntax colouring, code analysis.
- Console
    - Enter, interact with and visualize data, inside a command interpreter.
- Object Inspector
    - Automatically shows available documentation when the user is instantiating a class or calling a function
- Debugger and Variable Explorer
- History Log


### PyCharm IDE
- https://www.jetbrains.com/pycharm/
- Community edition available for free
- Most of its features are the same as of Spyder IDE
- Code analysis is very powerful

### Jupyter Notebook
- https://jupyter.org/
- Free
- Ideal for prototyping and quick learning
- Provides rich and interactive output. Supports HTML, Markdown, LaTeX, images and videos.
- Easy to use

**We will be using Jupyter Notebook during workshops**

## Jupyter Notebook quick start <a name="Jupyter"></a>

- For a quick tour click: `Help - User Interface Tour`
- Most used keyboard shortcuts:
    - `Ctrl + Enter` (`command + return` in Mac OS) to execute code in the current cell.
    - `Shift + Enter` (`shift + return` in Mac OS) to execture code in the current cell and move to the next one.
    - `a` and `b` to create a cell above or below the current one.
    - `Shift + Tab` (with curser next to a python function) to view the documentation of that function.  
- Full list of shortcuts can be found under `Help - Keyboard shortcuts`

In [ ]:
# TODO: execute this cell to see the main principles that influenced Python programming language 
import this

In [ ]:
# To demonstrate Shift + Tab hotkey execute this cell and then move to the next one
import numpy as np

In [ ]:
# Place cursor between brackets and press Shift + Tab (press Tab once again holding Shift to get additional info)
np.array([0])

## Package management <a name="PackageManagement"></a> - Anaconda Navigator

<span style="color:red">*Note: The computers in the lab already have a conda environment called `ELEN90088` for your use, make sure you activate that environment before installing any packages.*</span>

There are different tools for package management in Python:

<img src="img/pkg_mgmt.jpg" width=800px />

- Anaconda Navigator: https://docs.anaconda.com/anaconda/navigator/tutorials/manage-packages/. 
    - [Short instruction](./BYOD_Setup_Information.ipynb) 
    - **We will use Anaconda Navigator as the main python package management method**

- Command line:
    - If you wish to use command line, the alternative is (again within Anaconda):
https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html
    - As a last resort (for Anaconda environment), you can use the generic `pip` to install Python packages. There are two ways:
        1. From Operating System:
            - Open command prompt/console
                - `Ctrl + R` -> `cmd` -> `Enter` in Windows
                - `Terminal` app in Mac OS
                - `Ctrl + Alt + T` in Ubuntu Linux. For other Linux distributions please consult a corresponding documentation
            - Type `pip install <package_name>`

        2. From Jupyter Notebook:
            - Type `!pip install <package_name>`

        _Optional_. Also, you can execute any other command that can be run from the command line directly, i.e. 
        - `!python -V` prompts python interpreter version
        - `!ls` - is a standard command to list computer files in Unix and Unix-like operating systems.

### Example
- Type `!pip install numpy` in the cell below to install NumPy package.
- Press `Ctrl + Enter` (`Control` + `Return` on MacOS) to execute it
- Type `!pip list` in the next cell to list all packages that are installed in your current Conda environment
- Press `Ctrl + Enter` (`Control` + `Return` on MacOS) to execute it

In [ ]:
!pip install numpy

In [ ]:
!ls

In [ ]:
!python -V

## Learning Python - Online Resources <a name="LearningPython"></a>

### Python Language Resources and Tutorials
* [Python tutorial](https://docs.python.org/3/tutorial/index.html)
* [Library reference/documentation](https://docs.python.org/3/reference/index.html#reference-index)
* [Additional Python tutorials and learning resources](https://wiki.python.org/moin/BeginnersGuide/Programmers)
* [Numpy for Matlab Users](http://wiki.scipy.org/NumPy_for_Matlab_Users)
* [Getting started with Python for science](http://scipy-lectures.org/intro/index.html)
* [Kaggle - learn python](https://www.kaggle.com/learn/python)

### 10 - 20 minute tutorials
* [http://www.learnpython.org/](http://www.learnpython.org/)
* [http://www.stavros.io/tutorials/python/](http://www.stavros.io/tutorials/python/)
* [https://developers.google.com/edu/python/introduction](https://developers.google.com/edu/python/introduction)

### Markdown resources

* [https://en.wikipedia.org/wiki/Markdown](https://en.wikipedia.org/wiki/Markdown)
* [https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
* [https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html)

# A Brief Introduction to Python

## Elements of Python programming <a name="ElementsOfPythonProgramming"></a>

- Declare a variable `x` and assign it an integer value: `x = 5`.
- Comments start with `#` symbol, i.e. `# This is a comment`.

In [ ]:
x = 34.5 - 23 # right hand side can be an expression
y = "Hello" # or a string

z = 3 # let us assign it to an integer value and write a simple conditional statement
if z == 3 or y == "Hello":
    x = x + 1
    y = y + "World" # String concatenation
    print(y)
    print(x)

In [ ]:
# TODO: The code above outputs "HelloWorld" without spacing. Could you fix this?

In [ ]:
# TODO: Change the code above so that it outputs the result only when both `z == 3` and `y == "Hello"` are true.

In [ ]:
# TODO: Print "HelloWorld" when x = 999

### Variable assignment <a name="VariableAssignment"></a>

- The first assignment to a variable creates it. Variable types don’t need to be declared. Python figures out the variable types on its own. 
- Case sensitive, can not start with numbers
- No punctuation characters `@% $`
- Reserved words: `for, while, if, class, print, not, finally, lambda`
- _Optional_. Binding a variable in Python means setting a name to hold a **reference** to some
object.
- The basic printing command is `print()`

In [6]:
a = 5

# print value of a
print(a)

# Formatted output - pythonic way
print("Type: {}".format(type(a)))
print("Type:" .format(type(a)))

5
Type: <type 'int'>
Type:


Assignment uses `=` and comparison uses `==`

In [ ]:
# Compare these two:
a = 5 # assignment
b = 4 # assignment
b == a # comparison (returns True or False)
print(b == a)

For numbers `+ - * / %` are as expected

In [ ]:
print("a = {}, b = {}".format(a, b))
print("+ operation: {}".format(a + b))
print("- operation: {}".format(a - b))
print("* operation: {}".format(a * b))
print("/ operation: {}".format(a / b))
print("% operation: {}".format(a % b)) 

Logical operators are words `and, or, not` not symbols

In [1]:
a = True
b = False
print(a or b)
print(a and b)
print(not a)

True
False
False


### Basic Data Types <a name="BasicDataTypes"></a>

- Most commont data types
    - Integers: `x = 2`
    - Floats: `x = 3.456`
    - Strings: `s = "MyString"`
        - Can use “” or ‘’ to specify: `"abc"` or `'abc'`
        - Unmatched `'` can occur within the string, i.e. `"matt's"`
    
- Python determines the type of the reference automatically based on the data object assigned
to it.
- Names in Python do not have an intrinsic type. Objects have types.

In [8]:
# a is assigned to an integer 5
a = 5 

# b is a float number
b = 2.456 

# c is assigned to a string
c = "I'm a string" 

In [12]:
# TODO: identify type of c = a + b?
z = c # Answer is `2`, integer division
print(z)

I'm a string


In [ ]:
# TODO: 

In [ ]:
# TODO:

In [10]:
z = int(5 / 2) # Answer is `2`, integer division
print(z)

2


##### Whitespace
Whitespace is meaningful in Python: especially indentation and placement of newlines.
- Use a newline to end a line of code.
- Use `\` when must go to next line prematurely
- No braces `{}` to mark blocks of code in Python. Use consistent indentation instead:
```python
    if True: 
        print("True")
    else:
        print("False")
```
- Often a colon appears at the start of a new block. (E.g. for function and class definitions.)
 

### Data Structures Overview <a name="DataStructures"></a>

##### List
- A sequence of arbitraty objects
- List is created by enclosing them in square brackets: `["string", 4, 10.5]`
- List is an ordered (starting from zero onward) data structure
- Variety of methods: https://www.w3schools.com/python/python_ref_list.asp
- Good sources with many code examples: 
    - https://www.w3schools.com/python/python_lists.asp
    - https://www.tutorialspoint.com/python/python_lists.htm

In [ ]:
# create a simple list example
list_example = ["abc", 34, 4.34, 23]
print(list_example)

# access the second element in the list
print(list_example[1])

# Change the first element
list_example[0] = 100
print(list_example)

# 

##### Tuples

- A simple _immutable_ _ordered_ sequence of items
- Methods: https://www.w3schools.com/python/python_ref_tuple.asp
- Items can be of mixed types, including collection types

In [14]:
# create a simple tuple example
tuple_example = (23, 'abc', 4.56, (2,3), 'def')

# print its 3rd element
print(tuple_example[2])

4.56


What is **immutable**?

In [ ]:
# create a simple tuple
a = (1, 2, 3)
# attempt to change its second element to 5. Error!
a[1] = 5
print(a)

In [ ]:
# create a simple list
b = [1, 2, 3]
# attempt to change its second element to 5. All good.
b[1] = 5
print(b)

##### Strings
- A sequence of characters:
```python
st = "Hello World"
st = 'Hello World'
st = """This is a multi-line
string that uses triple quotes."""
```
- Broad library of methods, i.e. `len()`, `lower()`, `upper()`, etc. Full list is here: https://docs.python.org/release/2.5.2/lib/string-methods.html
- Good sources with code examples:
    - https://www.tutorialspoint.com/python/python_strings.htm
    - https://www.w3schools.com/python/python_strings.asp

In [1]:
# Operator + is used for string concatenation, i.e.
a = "good"
b = "morning"
print(a + " " + b)
print('{} {}'.format(a,b))

# TODO: what is the result of "42" + "69"?

good morning
good morning


Is `string` immutable?

In [ ]:
# TODO: check if string is immutable

_Optional_. Consider the following example. We create a string `a`, modify it, check the value of `a` and it has changed. Does this imply that `string` is actually a mutable type and we do not understand something? **No**. The trick is to check `id()` of the object that python creates. When the string `a` gets modified python creates a new object in a different part of memory. 

In [ ]:
a = "Hello"
a +=" World"
print(a)

In [2]:
a = "Hello"
identity_a = id(a)
a += " World"
new_identity_a = id(a)
if identity_a != new_identity_a:
    print("String is Immutable")

String is Immutable


- We can access individual members of a tuple, list, or string using square bracket “array” notation.
- Note that all are 0 based

In [15]:
print(tuple_example[1])
print(tuple_example[1:3])
print(list_example[1])
print(st[2:5]) 

abc
('abc', 4.56)


NameError: name 'list_example' is not defined

####  Dictionaries
* Dictionaries store a mapping between a set of keys and a set of values.
    * Keys can be any immutable type
    * Values can be any type
    * A single dictionary can store values of different types
* Each entry has
    * A **key**
    * A **value**
* No specific order
* Possible to add, remove, and modify the values
    * Example: telephone book

In [74]:
phonebook = {'Andrew':8806336, 'Emily':6784346, 'Peter':7658344, 'Lewis':1122345} # initialize dictionary
""print(phonebook) # print all key-value pairs
print(phonebook["Andrew"]) # print the value corresponding to the key "Andrew"
phonebook['Gingerbread'] = 1234567 # add a new key-value pair to the dictionary
print(phonebook) # print all key-value pairs
print(phonebook.get('Jason', 'N/A'))  # Get an element with a default; prints "N/A"
print(phonebook.get('Emily', 'N/A'))    # Get an element with a default; prints "6784346"""
del phonebook['Andrew'] # delete the entry with the given key
print(phonebook.get('Andrew', 'N/A')) # "fish" is no longer a key; prints "N/A"

N/A


### Conditional Statements <a name="ConditionalStatements"></a>

In [17]:
# if statement
def letterGrade(score):
    if score >= 90:
        letter = 'A'
    elif score >= 80:
        letter = 'B'
    elif score >= 70:
        letter = 'C'
    elif score >= 60:
        letter = 'D'
    else:
        letter = 'F'
    return letter

In [18]:
# while loop
temperature = 115
while temperature > 112: # first while loop code
    print(temperature)
    temperature = temperature - 1
print('The tea is cool enough.')

115
114
113
The tea is cool enough.


In [19]:
# for loop to iterate over a given sequence
languages = ["C", "C++", "Perl", "Python"]
for x in languages:
    print(x)

C
C++
Perl
Python


In [20]:
# If you want access to the index of each element within the body of a loop, use the built-in enumerate function
languages = ["C", "C++", "Perl", "Python"]
for idx, lang in enumerate(languages):
    print('{}: {}'.format(idx + 1, lang))

1: C
2: C++
3: Perl
4: Python


### Functions <a name="Functions"></a>
* Functions are a convenient way to
    * divide your code into useful blocks
    * Make the code readable
* `def` creates a function and assigns it a name
* `return` sends a result back to the caller
* Arguments are passed by assignment
* Arguments and return types are not declared

_Optional_. `*args` and `**kwargs` can be used to get arbitraty number of arguments in Python function. For more info please follow this [tutorial](https://pythontips.com/2013/08/04/args-and-kwargs-in-python-explained/)

In [21]:
# def <name>(arg1, arg2, ..., argN):
#     <statements>
#     return <value>

def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


#### Passing Arguments to Functions

* Arguments are passed by assignment
* Passed arguments are assigned to local names
* Assignment to argument names do not affect the caller
* Can define defaults for arguments that need not be passed

In [23]:
def hello(name, loud=False):
    if loud:
        print('HELLO, {}!'.format(name.upper()))
    else:
        print('Hello, {}'.format(name))

hello('Bob') # uses the default value for loud
hello('Fred', loud=True)

Hello, Bob
HELLO, FRED!


### Modules <a name="Modules"></a>
* Modules are functions and variables defined in separate files
* Items are imported using from or import

```python
from module import function
function()

import module
module.function()
```

#### Why use Modules?
* Module allows you to logically organize your Python code. Grouping related code into a module makes the code easier use.
* Implementing shared services or data
    * Can provide global data structure that is accessed by multiple subprograms

```python
# cal_module.py - a separate python file
# define some variables
input_1 = 1
input_2 = 2 

# define some functions
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b
```

```python
# calculator.py - current file name

import cal_module

cal_module.input_1 = 5
answer1 = cal_module.add(2, 3)
answer2 = cal_module.subtract(2,3)
```

### Classes and Objects <a name="ClassesandObjects"></a>
* A software item that contains variables and methods
* Objects are an encapsulation of variables and functions into a single entity
* Objects get their variables and functions from classes
* Classes are essentially a template to create your objects

In [24]:
class Greeter(object):
    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, {}!'.format(self.name.upper()))
        else:
            print('Hello, {}'.format(self.name))

In [25]:
g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method
g.greet(loud=True)   # Call an instance method

Hello, Fred
HELLO, FRED!


### Special Functions <a name="SpecialFunctions"></a>

### lambda <a name="Numpy"></a>
* A `lambda` function is a small anonymous function.
* A `lambda` function can take any number of arguments, but can only have one expression.
* Basic syntax
    * `lambda <arguments> : <expression>`
* `lambda` operator can have any number of arguments, but it can have only one expression. It cannot contain any statements and it returns a function object which can be assigned to any variable.

_Note_. There is not much difference between functions and lambda functions. **In our course we encourage you to use explicitly defined functions for readability.** For more details however, see the first answer [here](https://stackoverflow.com/questions/12264834/what-is-the-difference-for-python-between-lambda-and-regular-function).

In [26]:
# Example 1
def add(x, y): 
    return x + y
  
# Call the function
print(add(2, 3))

add_lambda = lambda x, y : x + y 
print(add_lambda(2, 3))

5
5


In [27]:
# you have a function definition that takes one argument
# that argument will be multiplied with an unknown number
def myfunc(n):
  return lambda a : a * n

# create the function mydoubler that multiplies an argument by 2
mydoubler = myfunc(2)
# give 11 as the argument
print(mydoubler(11))

# create the function mytripler that multiplies an argument by 3
mytripler = myfunc(3)
# give 11 as the argument
print(mytripler(11))

22
33


## External Libraries <a name="Libraries"></a>

### Numpy <a name="Numpy"></a>
Numpy is the core library for scientific computing in Python. It provides high-performance multidimensional array objects, and tools for working with these arrays.

In [28]:
import numpy as np        #import the numpy library to access it's functions

a = np.array([1, 2, 3])   # Create a rank 1 array
print(a.shape)            
print(a[0], a[1], a[2])   # Print each element
a[0] = 5                  # Change an element of the array
print(a)                  

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

(3,)
(1, 2, 3)
[5 2 3]
(2, 3)
(1, 2, 4)


In [29]:
# numpy functions that can be used to create arrays
a = np.zeros((2,2))   # Create an array of all zeros
print(a)                                

b = np.ones((1,2))    # Create an array of all ones
print(b)             

c = np.full((2,2), 7)  
print(c)              

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[ 7.  7.]
 [ 7.  7.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.77979192  0.52323369]
 [ 0.58519623  0.18180575]]


C:\Anaconda2\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


#### Array indexing
Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [30]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


#### Numpy datatypes
Every Numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype.

In [31]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         

int32
float64
int64


#### Array math
Basic mathematical functions operate elementwise on arrays, and are available as functions in the numpy module.

In [35]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum
print(x + y)
print(np.add(x, y))

# Elementwise difference
print(x - y)
print(np.subtract(x, y))

# Elementwise product
print(x * y)
print(np.multiply(x, y))

# Elementwise division
print(x / y)
print(np.divide(x, y))

# Elementwise square root
print(np.sqrt(x))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


Note that `*` is elementwise multiplication, not matrix multiplication. We instead use the `np.dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. `np.dot` is available both as a function in the Numpy module and as an instance method of array objects. 

Another alternative is to use the operator `@` for matrix multiplication. 

_Note_. `@` and `np.dot` give the same result for vectors and matrices. However they operate differently in general N-dimnetional case. More details can be found [here](https://stackoverflow.com/questions/34142485/difference-between-numpy-dot-and-python-3-5-matrix-multiplication#34142617).

In [34]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors
print(v.dot(w))
print(np.dot(v, w))
print(v@w)

# Matrix / vector product
print(x.dot(v))
print(np.dot(x, v))
print(x@v)

# Matrix / matrix product
print(x.dot(y))
print(np.dot(x, y))
print(x@y)


SyntaxError: invalid syntax (<ipython-input-34-1a8813d0f980>, line 10)

Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:

In [36]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements
print(np.sum(x, axis=0))  # Compute sum of each column
print(np.sum(x, axis=1))  # Compute sum of each row

10
[4 6]
[3 7]


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object

In [37]:
x = np.array([[1,2], [3,4]])
print(x)      
print(x.T)  

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    
print(v.T)  

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


### Matplotlib <a name="Matplotlib"></a>
Matplotlib is a Python 2D plotting library which produces publication quality figures in a variety of formats and interactive environments across platforms. Matplotlib can be used in Python scripts, the Python and IPython shells, the Jupyter notebook, web application servers, and four graphical user interface toolkits.

In [69]:
# install matplotlib via pip first
import matplotlib.pyplot as plt
import numpy as np

# x values to be plotted, see documentation
x = np.linspace(0, 2, 100)

# get the corresponding y values for each x value
y1 = x # y = x plot
y2 = x**2 # y = x^2 plot
y3 = x**3 # y = x^3 plot

plt.plot(x, y1, label='linear')
plt.plot(x, y2, label='quadratic')
plt.plot(x, y3, label='cubic')

plt.xlabel('x label')
plt.ylabel('y label')

plt.title("Simple Plot")

plt.legend()

plt.show()

#### [Multiple subplots](https://matplotlib.org/gallery/subplots_axes_and_figures/subplot.html)
Simple demo with multiple subplots.

In [42]:
x1 = np.linspace(0.0, 5.0)
x2 = np.linspace(0.0, 2.0)

y1 = np.cos(2 * np.pi * x1) * np.exp(-x1)
y2 = np.cos(2 * np.pi * x2)

# plot y1 against x1
plt.subplot(2, 1, 1)
plt.plot(x1, y1, 'o-')
plt.title('A tale of 2 subplots')
plt.ylabel('Damped oscillation')

# plot y2 against x2
plt.subplot(2, 1, 2)
plt.plot(x2, y2, '.-')

plt.xlabel('time (s)')
plt.ylabel('Undamped')

plt.show()

#### [3D surface (color map)](https://matplotlib.org/gallery/mplot3d/surface3d.html)

In [70]:
# This import registers the 3D projection, but is otherwise unused.
-

### Scipy <a name="Scipy"></a>
* Contains various toolboxes dedicated to common issues in scientific computing
    * integration, optimization, image processing, statistics, special functions (fft) etc.
* numpy and scipy work hand in hand. It is meant to operate efficiently on numpy arrays

In [44]:
# install scipy using pip first
# Example -  find and plot the maximum of a Bessel function
from scipy import special, optimize

# returns the Bessel function value to the coresponding x
f = lambda x: -special.jv(3, x)
# note that the function finds the minimum, therefore we negate the Bessel function (see above line)
sol = optimize.minimize(f, 1.0)

# Plot
x = np.linspace(0, 10, 5000)
# Here, we plot the positive Bessel function
plt.plot(x, special.jv(3, x), '-', sol.x, -sol.fun, 'o')

## Report

You will not submit any reports for this workshop. You can show your number guessing game to your demonstrator and get his/her feedback.

## Exercise - Number Guessing Game <a name="Exercise"></a>

Write a number guessing game (function) to find a random real number on the interval $[0,1]$ up to a given $0<\epsilon \ll 1$ accuracy.

**Input** to the program: $0<\epsilon \ll 1$ (your program should generate a random number within $[0,1]$)

**Output**: the sequence of guesses, the original number, and the number you have found with your algorithm.

*Hints: consider an efficient algorithm, stopping criterion etc.*

The integer version of the game is discussed at: <br> https://www.khanacademy.org/computing/computer-science/algorithms/intro-to-algorithms/a/a-guessing-game <br>
as well as in many other places on the Internet!

In [73]:
import numpy as np
e = np.random.random(1)  # Create an array filled with random values
ming=0
maxg=1.0
guess=(ming+maxg)/2
epsilon=0.00000001;
count1=0
print(e) 
while (abs(guess-e)) > epsilon:
    count1+=1
    if e < guess: 
        maxg=guess
    else:
        ming=guess       
    guess=(ming+maxg)/2 
print(guess)
print(count1)



[ 0.11610863]
0.116108626127
24
